tracker: ../lib/csapp.c ../lib/csapp.h recv_mem.c recv_mem.h sort_mem.c sort_mem.h to_client.c to_client.h listening_from_worker.h listening_from_worker.c show_mem.c show_mem.h tracker.c
	gcc tracker.c ../lib/csapp.c ../lib/csapp.h recv_mem.c recv_mem.h sort_mem.c sort_mem.h to_client.c to_client.h listening_from_worker.h listening_from_worker.c show_mem.c show_mem.h -o tracker -lpthread
clean:
	-rm -rf *.o tracker
